export const seedCategories = [
  { name: 'Tech & Innovation', slug: 'tech-innovation', icon: 'Cpu', color: 'from-blue-500 to-indigo-600' },
  { name: 'Cultural & Arts', slug: 'cultural-arts', icon: 'Palette', color: 'from-pink-500 to-rose-600' },
  { name: 'Competitions & Hackathons', slug: 'competitions', icon: 'Trophy', color: 'from-amber-500 to-orange-600' },
  { name: 'Seminars & Workshops', slug: 'seminars-workshops', icon: 'GraduationCap', color: 'from-purple-500 to-violet-600' },
  { name: 'Career & Networking', slug: 'career-networking', icon: 'Briefcase', color: 'from-emerald-500 to-teal-600' },
  { name: 'Sports & Fitness', slug: 'sports', icon: 'Activity', color: 'from-green-500 to-emerald-600' },
];

export const seedDepartments = [
  'Computer Science & Engineering',
  'Electrical & Electronic Engineering',
  'Software Engineering',
  'Information Technology',
  'Business Administration (BBA)',
  'Economics',
  'Civil Engineering',
  'Pharmacy',
  'English Literature',
  'Law & Justice',
];

export const seedClubs = [
  {
    name: 'Computer & Programming Club (CPC)',
    slug: 'cpc',
    description: 'Empowering students in competitive programming, software development, and AI hackathons.',
    category: 'Technology',
    logo: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1000&auto=format&fit=crop&q=80',
    department: 'Computer Science & Engineering',
    establishedYear: 2018,
    presidentName: 'Sadia Afrin',
    presidentEmail: 'club@university.edu',
    contactEmail: 'cpc@university.edu',
    memberCount: 420,
    socialLinks: { facebook: 'https://facebook.com', linkedin: 'https://linkedin.com' },
    status: 'active' as const,
  },
  {
    name: 'IEEE Student Branch',
    slug: 'ieee-sb',
    description: 'Fostering technological innovation and excellence for the benefit of humanity.',
    category: 'Engineering & Science',
    logo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=1000&auto=format&fit=crop&q=80',
    department: 'Electrical & Electronic Engineering',
    establishedYear: 2017,
    presidentName: 'Nahid Hasan',
    presidentEmail: 'nahid.ieee@university.edu',
    contactEmail: 'ieee@university.edu',
    memberCount: 310,
    socialLinks: { facebook: 'https://facebook.com', linkedin: 'https://linkedin.com' },
    status: 'active' as const,
  },
  {
    name: 'University Cultural Club (আমার অনুষ্ঠান)',
    slug: 'cultural-club',
    description: 'Celebrating cultural heritage, music, dance, drama, and festive occasions across campus.',
    category: 'Cultural & Arts',
    logo: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1000&auto=format&fit=crop&q=80',
    department: 'General & Arts',
    establishedYear: 2015,
    presidentName: 'Rakib Hasan',
    presidentEmail: 'rakib.culture@university.edu',
    contactEmail: 'culture@university.edu',
    memberCount: 580,
    socialLinks: { facebook: 'https://facebook.com' },
    status: 'active' as const,
  },
  {
    name: 'Robotics & Automation Society',
    slug: 'robotics-society',
    description: 'Building autonomous robots, IoT hardware, drone tech, and competing in national RoboWars.',
    category: 'Technology',
    logo: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?w=1000&auto=format&fit=crop&q=80',
    department: 'Robotics & Mechatronics',
    establishedYear: 2019,
    presidentName: 'Fahim Faisal',
    presidentEmail: 'fahim.robotics@university.edu',
    contactEmail: 'robotics@university.edu',
    memberCount: 260,
    socialLinks: { facebook: 'https://facebook.com' },
    status: 'active' as const,
  },
  {
    name: 'University Debating Society',
    slug: 'debating-society',
    description: 'Enhancing analytical thinking, public speaking, and parliamentary debate skills.',
    category: 'Academic & Literary',
    logo: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=200&auto=format&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1000&auto=format&fit=crop&q=80',
    department: 'Law & Justice',
    establishedYear: 2016,
    presidentName: 'Tanzina Ahmed',
    presidentEmail: 'tanzina.debate@university.edu',
    contactEmail: 'debate@university.edu',
    memberCount: 195,
    socialLinks: { facebook: 'https://facebook.com' },
    status: 'active' as const,
  },
];

export const seedEvents = [
  {
    title: 'National University Tech Fest 2026',
    slug: 'national-university-tech-fest-2026',
    shortDescription: 'The flagship annual technology festival featuring Hackathons, Gaming Contests, and AI Project Showcases.',
    description: `Welcome to the grandest technology extravaganza of the year! The National University Tech Fest 2026 brings together over 1,500 aspiring software engineers, hardware innovators, and tech enthusiasts from 40+ universities across Bangladesh.

Highlights include:
- 24-Hour AI & Web3 Hackathon with ৳ 200,000 in cash prizes
- Inter-University Competitive Programming Contest (IUPC)
- Project Showcasing (Robotics, IoT, Healthcare Tech)
- E-Sports Tournament (Valorant & FIFA 26)
- Keynote talks from Silicon Valley & local tech industry leaders

Food, exclusive t-shirt, swag pack, and official certificate included for all registered participants.`,
    coverImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&auto=format&fit=crop&q=80',
    category: 'Tech & Innovation',
    department: 'Computer Science & Engineering',
    eventType: 'offline' as const,
    venue: 'University Central Auditorium & CSE Labs',
    building: 'Dr. Qudrat-i-Khuda Academic Complex',
    room: 'Auditorium Hall 1 & Lab 401-406',
    mapUrl: 'https://maps.google.com',
    startAt: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // In 5 days
    endAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    capacity: 500,
    registeredCount: 385,
    waitlistCount: 12,
    isWaitlistEnabled: true,
    registrationFee: 500,
    isFeeRequired: true,
    status: 'published' as const,
    featured: true,
    speakers: [
      {
        name: 'Dr. Mohammad Kaykobad',
        designation: 'Distinguished Professor & ACM Fellow',
        organization: 'Dept of CSE, BUET',
        photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
        bio: 'Pioneer of competitive programming and algorithmic training in Bangladesh.',
      },
      {
        name: 'Tanvir Hossain',
        designation: 'Lead AI Engineer',
        organization: 'Google Research',
        photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
        bio: 'Expert in Large Language Models and Multimodal GenAI architectures.',
      },
    ],
    agenda: [
      { time: '09:00 AM', title: 'Registration & Welcome Kit Collection', speaker: 'Volunteer Desk' },
      { time: '10:00 AM', title: 'Grand Opening Ceremony', speaker: 'Vice Chancellor & Chief Guest' },
      { time: '11:00 AM', title: 'Keynote: The Future of AI in South Asia', speaker: 'Dr. Mohammad Kaykobad' },
      { time: '01:00 PM', title: 'Networking Lunch & Project Expo', speaker: 'Cafeteria Lawn' },
      { time: '02:30 PM', title: 'Hackathon Commences (24hr Sprint)', speaker: 'Lab Coordinators' },
      { time: '06:00 PM', title: 'Cultural Performance & Gaming Prelims', speaker: 'Cultural Club' },
    ],
    requirements: ['Valid Student ID card', 'Laptop with development environment', 'Registration QR Ticket'],
    rules: ['Code of conduct strictly enforced', 'No plagiarism in hackathon submissions', 'Badge must be visible at all times'],
    faq: [
      { question: 'Will food be provided during the hackathon?', answer: 'Yes, breakfast, lunch, dinner, snacks, and continuous coffee will be provided.' },
      { question: 'Can students from other departments register?', answer: 'Absolutely! Students from all faculties and departments are welcome.' },
    ],
  },
  {
    title: 'University Cultural Gala & Spring Fest (বসন্ত উৎসব ২০২৬)',
    slug: 'university-cultural-gala-spring-fest-2026',
    shortDescription: 'A vibrant evening of traditional music, poetry recitation, drama, dance, and live band performances.',
    description: `Celebrate the colorful arrival of Spring with "আমার অনুষ্ঠান - বসন্ত উৎসব ২০২৬". Enjoy scintillating musical performances by prominent student vocalists, renowned folk artists, drama stage productions, and an electrifying headline band performance.

Dress code: Festive Traditional (Yellow, Red, Floral).
Special food stalls with traditional delicacies will be open throughout the day.`,
    coverImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200&auto=format&fit=crop&q=80',
    category: 'Cultural & Arts',
    department: 'General & Arts',
    eventType: 'offline' as const,
    venue: 'University Open Amphitheatre',
    building: 'Student Activity Center',
    room: 'Main Amphitheatre Ground',
    mapUrl: 'https://maps.google.com',
    startAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    endAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
    capacity: 1200,
    registeredCount: 890,
    waitlistCount: 0,
    isWaitlistEnabled: true,
    registrationFee: 200,
    isFeeRequired: true,
    status: 'published' as const,
    featured: true,
    speakers: [
      {
        name: 'Shironamhin (Guest Band)',
        designation: 'Renowned Progressive Rock Band',
        organization: 'Bangladesh Music Industry',
        photo: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200&auto=format&fit=crop&q=80',
        bio: 'Legendary musical performance for the closing concert.',
      },
    ],
    agenda: [
      { time: '03:00 PM', title: 'Gate Opening & Art Exhibition', speaker: 'Art Society' },
      { time: '04:30 PM', title: 'Traditional Folk & Rabindra Sangeet', speaker: 'Student Artists' },
      { time: '06:30 PM', title: 'Drama: "নকশী কাঁথার মাঠ"', speaker: 'Drama Troupe' },
      { time: '08:00 PM', title: 'Headline Band Concert', speaker: 'Shironamhin' },
    ],
    requirements: ['Valid QR Pass', 'Traditional Attire encouraged'],
    rules: ['No outside food inside amphitheatre', 'Strict security screening at entrance'],
    faq: [{ question: 'Can alumni attend?', answer: 'Yes, alumni can register with their Alumni ID.' }],
  },
  {
    title: 'Generative AI & LLM Engineering Masterclass',
    slug: 'generative-ai-llm-engineering-masterclass',
    shortDescription: 'Hands-on deep dive into building production RAG systems, Fine-tuning Llama-3, and deploying AI Agents.',
    description: `Step into the frontier of Artificial Intelligence. This intensive 2-day workshop gives students practical experience building scalable LLM applications, Vector databases, LangChain/LlamaIndex pipelines, and agentic workflows using Google Gemini and OpenAI APIs.`,
    coverImage: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=1200&auto=format&fit=crop&q=80',
    category: 'Seminars & Workshops',
    department: 'Computer Science & Engineering',
    eventType: 'hybrid' as const,
    venue: 'Seminar Hall 3 & Zoom Live',
    building: 'ICT Building 2nd Floor',
    room: 'Room 204',
    mapUrl: 'https://maps.google.com',
    startAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    endAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
    capacity: 150,
    registeredCount: 150,
    waitlistCount: 24,
    isWaitlistEnabled: true,
    registrationFee: 300,
    isFeeRequired: true,
    status: 'published' as const,
    featured: true,
    speakers: [
      {
        name: 'Arif Chowdhury',
        designation: 'Principal Machine Learning Scientist',
        organization: 'BrainStation 23',
        photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
        bio: 'Specialist in enterprise generative AI architectures.',
      },
    ],
    agenda: [
      { time: '10:00 AM', title: 'Architecture of Modern Transformer Models', speaker: 'Arif Chowdhury' },
      { time: '11:30 AM', title: 'Hands-on RAG (Retrieval-Augmented Generation)', speaker: 'Lab Mentors' },
      { time: '02:00 PM', title: 'Autonomous Multi-Agent Systems & Tool Calling', speaker: 'Arif Chowdhury' },
    ],
    requirements: ['Basic Python proficiency', 'Personal laptop'],
    rules: ['Attendance required for certificate eligibility'],
    faq: [{ question: 'Will recorded sessions be available?', answer: 'Yes, recorded materials will be sent to enrolled participants.' }],
  },
  {
    title: 'Inter-University Programming Contest (IUPC 2026)',
    slug: 'inter-university-programming-contest-2026',
    shortDescription: 'Premier 5-hour competitive programming battle following ICPC regional guidelines.',
    description: `Test your algorithmic problem-solving speed and team synchronization in the IUPC 2026. Teams of 3 will solve 10 challenging algorithmic problems covering Dynamic Programming, Graph Theory, Number Theory, and Geometry.`,
    coverImage: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1200&auto=format&fit=crop&q=80',
    category: 'Competitions & Hackathons',
    department: 'Computer Science & Engineering',
    eventType: 'offline' as const,
    venue: 'Main Software Engineering Computer Lab',
    building: 'Science Building',
    room: 'Lab 501',
    startAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    endAt: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000 + 7 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
    capacity: 300,
    registeredCount: 210,
    waitlistCount: 0,
    isWaitlistEnabled: false,
    registrationFee: 0,
    isFeeRequired: false,
    status: 'published' as const,
    featured: false,
    speakers: [],
    agenda: [
      { time: '09:00 AM', title: 'Mock Contest & Environment Setup', speaker: 'Judging Panel' },
      { time: '11:00 AM', title: 'Official 5-Hour Contest Kickoff', speaker: 'Chief Judge' },
      { time: '04:00 PM', title: 'Scoreboard Freeze & Solution Discussion', speaker: 'Problem Setters' },
      { time: '05:30 PM', title: 'Prize Giving & Champion Trophy', speaker: 'Dean of Science' },
    ],
    requirements: ['Team of 3 students', 'University ID'],
    rules: ['ICPC regional rules apply'],
    faq: [],
  },
  {
    title: 'Annual Career Expo & Corporate Networking 2026',
    slug: 'annual-career-expo-corporate-networking-2026',
    shortDescription: 'Connect directly with HR leaders and technical recruiters from 50+ multinational and top tech companies.',
    description: `Bridging the gap between university graduates and industry opportunities. Drop your CV, attend on-the-spot interviews, participate in mock HR panels, and discover full-time positions and paid internships.`,
    coverImage: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80',
    category: 'Career & Networking',
    department: 'Business Administration (BBA)',
    eventType: 'offline' as const,
    venue: 'University Plaza & Conference Center',
    building: 'Admin & Business Tower',
    room: 'Grand Ballroom',
    startAt: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    endAt: new Date(Date.now() + 26 * 24 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000),
    capacity: 800,
    registeredCount: 620,
    waitlistCount: 0,
    isWaitlistEnabled: true,
    registrationFee: 0,
    isFeeRequired: false,
    status: 'published' as const,
    featured: true,
    speakers: [
      {
        name: 'Rubana Huq',
        designation: 'Managing Director & Industry Leader',
        organization: 'Mohammadi Group',
        photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
        bio: 'Keynote on career adaptability and leadership in a changing global economy.',
      },
    ],
    agenda: [
      { time: '10:00 AM', title: 'Inauguration & Keynote Speech', speaker: 'Rubana Huq' },
      { time: '11:30 AM', title: 'Corporate Booth Visits & CV Drop', speaker: 'Recruiters' },
      { time: '02:00 PM', title: 'Panel: What Silicon Valley & Big Tech Look For', speaker: 'Industry Experts' },
    ],
    requirements: ['Printed CV copies', 'Formal attire'],
    rules: ['Punctuality requested for scheduled interview slots'],
    faq: [],
  },
  {
    title: 'Inter-Department Football Championship 2026',
    slug: 'inter-department-football-championship-2026',
    shortDescription: 'The ultimate athletic showdown between all academic departments for the Chancellor Trophy.',
    description: `Cheer for your department! 16 department teams compete over 5 days in knockout football matches. High energy, spirited chants, and live commentary.`,
    coverImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80',
    category: 'Sports & Fitness',
    department: 'Physical Education & Sports',
    eventType: 'offline' as const,
    venue: 'University Central Sports Ground',
    building: 'Sports Complex',
    room: 'Main Stadium',
    startAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    endAt: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
    registrationDeadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
    capacity: 2000,
    registeredCount: 1450,
    waitlistCount: 0,
    isWaitlistEnabled: true,
    registrationFee: 0,
    isFeeRequired: false,
    status: 'published' as const,
    featured: false,
    speakers: [],
    agenda: [
      { time: '03:00 PM', title: 'Opening Match: CSE vs EEE', speaker: 'Sports Club' },
      { time: '05:00 PM', title: 'Match 2: BBA vs Law', speaker: 'Sports Club' },
    ],
    requirements: ['Spectator Pass / Student ID'],
    rules: ['Sportsman spirit is mandatory'],
    faq: [],
  },
];
